#!/bin/bash

mkdir /tmp/ci/build/ && cd /tmp/ci/build/ 
chmod -R 0777 .
export ARCH_ARM_HAVE_TLS_REGISTER=true
export TARGET_CPU_SMP=true
export WITH_JIT=true
export JS_ENGINE=v8 
export USE_CCACHE=1
ccache -M 200G

repo init -u git://github.com/crdroidandroid/android.git -b 11.0 --depth=1 --groups=all,-notdefault,-device,-darwin,-x86,-mips

repo sync -c -j48 --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync